<a href="https://colab.research.google.com/github/Sabra7/py_labs/blob/main/lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

7.2 Creating Arrays from Existing Data

In [ ]:
my_list = [1, 2, 3, 4, 5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


7.3 Array Attributes

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("dtype:", arr.dtype)

ndim: 2
shape: (2, 3)
size: 6
dtype: int64


7.4 Filling Arrays with Specific Values

In [ ]:
zeros_array = np.zeros((3, 4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


7.5 Creating Arrays from Ranges

In [ ]:
arr = np.arange(10, 101, 10)
print(arr)

[ 10  20  30  40  50  60  70  80  90 100]


7.6 List vs. Array Performance: Introducing %timeit

In [ ]:
list1 = list(range(100000))
list2 = list(range(100000))
%timeit [x + y for x, y in zip(list1, list2)]

arr1 = np.arange(100000)
arr2 = np.arange(100000)
%timeit arr1 + arr2

7.01 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
76.9 µs ± 4.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


7.7 Array Operators

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("Addition:", arr1 + arr2)
print("Multiplication:", arr1 * arr2)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]


7.8 NumPy Calculation Methods

In [ ]:
arr = np.array([10, 25, 5, 40, 30])

print("Minimum:", arr.min())
print("Maximum:", arr.max())
print("Mean:", arr.mean())
print("Sum:", arr.sum())

Minimum: 5
Maximum: 40
Mean: 22.0
Sum: 110


7.9 Universal Functions

In [ ]:
arr = np.array([1, 4, 9, 16, 25])
result = np.sqrt(arr)

print(result)

[1. 2. 3. 4. 5.]


7.10 Indexing and Slicing

In [ ]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("First row:", arr[0, :])
print("Last column:", arr[:, -1])

First row: [10 20 30]
Last column: [30 60 90]


7.11 Views: Shallow Copies

In [ ]:
original = np.array([10, 20, 30, 40])
view_arr = original.view()

view_arr[0] = 999

print("View:", view_arr)
print("Original:", original)

View: [999  20  30  40]
Original: [999  20  30  40]


7.12 Deep Copies

In [ ]:
original = np.array([10, 20, 30, 40])
copy_arr = original.copy()

copy_arr[0] = 999

print("Copy:", copy_arr)
print("Original:", original)

Copy: [999  20  30  40]
Original: [10 20 30 40]


7.13 Reshaping and Transposing

In [ ]:
arr = np.arange(12)
reshaped = arr.reshape(3, 4)

print("Reshaped (3x4):\n", reshaped)
print("\nTransposed:\n", reshaped.T)

Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
